# Site settings
title: Олег Гордиенко — Пластический хирург
url: https://gordienko.github.io
description: Сертифицированный пластический хирург. Член Российского общества пластических, реконструктивных и эстетических хирургов (РОПРЭХ).
lang: ru-RU

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
bg-url:
  intro: https://i.ibb.co/ScrBGGY/intro-bg.jpg
  downloads: https://i.ibb.co/MSPFtbZ/downloads-bg.jpg

# Footer settings
footer: Олег Гордиенко

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - handler: vk
    title: ovgordienko
    url: https://vk.me/ovgordienko

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
optional_front_matter:
  remove_originals: false
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
